---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Cloudformation Stack which create four endpoints in order to enable 
SSM Agent in Private subnets."

Resources:

  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      RouteTableIds:
        - !ImportValue PrivateRouteTableAppInternet
      ServiceName: !Join 
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
      VpcId: !ImportValue VPCInternet

  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !ImportValue VPCInternet
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !ImportValue PrivateOneInternet
        - !ImportValue PrivateTwoInternet
      SecurityGroupIds: 
        - !ImportValue SGEndpointsInternet

  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !ImportValue VPCInternet
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !ImportValue PrivateOneInternet
        - !ImportValue PrivateTwoInternet
      SecurityGroupIds: 
        - !ImportValue SGEndpointsInternet

  EC2Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !ImportValue VPCInternet
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !ImportValue PrivateOneInternet
        - !ImportValue PrivateTwoInternet
      SecurityGroupIds: 
        - !ImportValue SGEndpointsInternet

  SSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !ImportValue VPCInternet
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: 
        - !ImportValue PrivateOneInternet
        - !ImportValue PrivateTwoInternet
      SecurityGroupIds: 
        - !ImportValue SGEndpointsInternet