---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Cloudformation Stack which create four endpoints in order to enable 
SSM Agent in Private subnets."

Resources:

  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      RouteTableIds:
        - !ImportValue PrivateRouteTableAppInternet
      ServiceName: !Join 
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
      VpcId: !ImportValue VPCInternet
