---
AWSTemplateFormatVersion: 2010-09-09

Description: 
  Template which create an RDS Cluster

Parameters:

  MasterUsername:
    Type: String
    Default: demoDRP

  DBInstanceType:
    Type: String
    Default: db.t2.small
    AllowedValues: [db.t2.small, db.t2.medium, db.t3.small, db.t3.medium,
    db.r3.large,db.r4.large,db.r5.large]

  Engine:
    Type: String
    Default: aurora
    AllowedValues: [aurora]
      
Resources:
 
  DatabaseReplicaInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: !Ref Engine
      DBClusterIdentifier: !ImportValue "DatabaseCluster"
      DBInstanceClass: !Ref DBInstanceType
      DBSubnetGroupName: !ImportValue "DatabaseSubnetGroup"