---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Cloudformation Stack which create: 
VPC of Application
- VPC 
- 2 Private Subnets
- Route Table for private subnets
- NACL
"

#==========================================================================
Parameters:

  AppName: 
    Description: Applications Name
    Type: String
    Default: "DRP"
 
  AZ1:
    Description: Availability Zone 1
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-1a"

  AZ2:
    Description: Availability Zone 2
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "us-east-1b"

  VPCCidr:
    Description: Virtual Network Cloud
    Type: String
    Default: 192.16.0.0/16

  PublicCidrOne:
    Description: Public Subnet CIDR
    Type: String
    Default: 192.16.1.0/24

  PublicCidrTwo:
    Description: Public Subnet CIDR
    Type: String
    Default: 192.16.2.0/24
  
  PrivateOneCidr:
    Description: VPC_CIDR
    Type: String
    Default: 192.16.3.0/24

  PrivateTwoCidr:
    Description: VPC_CIDR
    Type: String
    Default: 192.16.4.0/24

  PrivateThreeCidr:
    Description: VPC_CIDR
    Type: String
    Default: 192.16.5.0/24

  PrivateFourCidr:
    Description: VPC_CIDR
    Type: String
    Default: 192.16.6.0/24

#==========================================================================
Resources:
 
  PublicRoute: 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: "rtb-041c564720d2a4af3"
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: igw-0d6e8f08e6ba3f1a0


  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc  

  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - EIP
        - AllocationId
      SubnetId: "subnet-0c67e000f417f8a55"
      Tags:
        - Key: NatGateway
          Value: NatGateway

  NatRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: "rtb-0a9bbf3c1d52a5d2c"
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NAT

#==========================================================================
Outputs:
  VPC:
    Description: "VPCId of the newly created VPC"
    Value: "vpc-05491ab59f259dadc"
    Export:
      Name: VPCInternet

  PrivateOne:
    Description: "Private Subnet in AZ1"
    Value: "subnet-08ac8d1c9b26e59e0"
    Export:
      Name: PrivateOneInternet

  PrivateTwo:
    Description: "Private Subnet in AZ2"
    Value: "subnet-0f060183861efc4a1"
    Export:
      Name: PrivateTwoInternet

  PrivateThree:
      Description: "Private Subnet in AZ1"
      Value: "subnet-04393790d48612654"
      Export:
        Name: PrivateThreeInternet

  PrivateFour:
      Description: "Private Subnet in AZ2"
      Value: "subnet-0560a272a6124ec7e"
      Export:
        Name: PrivateFourInternet

  PublicOne:
    Description: "Public Subnet in AZ1"
    Value: "subnet-0c67e000f417f8a55"
    Export:
      Name: PublicOneInternet

  PublicTwo:
    Description: "Public Subnet in AZ2"
    Value: "subnet-0c2e371a7c31ff573"
    Export:
      Name: PublicTwoInternet
  
  AZ1:
    Description: "AZ 1"
    Value: "us-east-1a"
    Export:
      Name: AZ1Internet

  AZ2:
    Description: "AZ 2"
    Value: "us-east-1b"
    Export:
      Name: AZ2Internet
  
  AppName:
    Description: "Applications Name"
    Value: "DemoInfra"
    Export:
      Name: AppNameInternet
  
  VPCCidr:
    Description: VPC Cidr
    Value: "192.16.0.0/16"
    Export:
      Name: APPVPCCidrInternet

  PrivateRouteTableApp:
    Description: RouteTable for EC2 instances
    Value: "rtb-0a9bbf3c1d52a5d2c"
    Export: 
      Name: PrivateRouteTableAppInternet