---
- name: Provisioning of java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Copy jars from S3 bucket
  shell: |
    aws s3 cp s3://thunderhacks-builds/ms-jars/ /home/ec2-user/ms-jars/ --recursive
    
- name: Copy services from bucket
  shell: |
    aws s3 cp s3://thunderhacks-builds/services/ /etc/systemd/system/ --recursive
    
- name: Ensure server is enabled
  service:
    name: server
    state: started
    enabled: true

- name: Ensure accounts is enabled
  service:
    name: accounts
    state: started
    enabled: true

- name: Ensure buddy is enabled
  service:
    name: buddy
    state: started
    enabled: true

- name: Ensure games is enabled
  service:
    name: games
    state: started
    enabled: true

- name: Ensure products is enabled
  service:
    name: products
    state: started
    enabled: true

- name: Ensure user is enabled
  service:
    name: user
    state: started
    enabled: true

- name: Ensure url is enabled
  service:
    name: url
    state: started
    enabled: true
