---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an Cluster Database"

#TODO Add ParameterStore to DNSs, user, DatabasePassword

Parameters:

  DatabaseName:
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"

  DatabaseUser:
    Type: String
    MinLength: 1
    MaxLength: 16
    Default: pgpool
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"

  DatabasePassword:
    Type: String
    MinLength: 8
    MaxLength: 41
    Default: pgp0o1Cred
    NoEcho: true
    AllowedPattern: "[a-zA-Z0-9]*"

  DbInstanceSize:
    Type: String
    Description: Database instance size
    AllowedValues:
      - db.t2.small
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Default: "db.t2.small"

  ProjectTag:
    Type: String
    Description: Tag to apply to created resources for visibility
    Default: DemoDatabase

Resources:

  DBAuroraCluster:
    Type: "AWS::RDS::DBCluster"
    DependsOn: DBClusterParams
    Properties:
      DatabaseName: !Ref DatabaseName
      Engine: aurora-mysql
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      DBSubnetGroupName: !Ref DBSubnets
      DBClusterParameterGroupName: !Ref DBClusterParams
      VpcSecurityGroupIds:
        - !ImportValue AuroraSG
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  DBAuroraOne:
      Type : "AWS::RDS::DBInstance"
      DependsOn: DBParamGroup
      Properties:
        DBClusterIdentifier: !Ref DBAuroraCluster
        Engine: aurora-mysql
        DBInstanceClass: !Ref DbInstanceSize
        DBSubnetGroupName: !Ref DBSubnets
        DBParameterGroupName: !Ref DBParamGroup
        Tags:
          - Key: Project
            Value: !Ref ProjectTag

  DBAuroraTwo:
    Type : "AWS::RDS::DBInstance"
    DependsOn: DBParamGroup
    Properties:
      DBClusterIdentifier: !Ref DBAuroraCluster
      Engine: aurora-mysql
      DBInstanceClass: !Ref DbInstanceSize
      DBSubnetGroupName: !Ref DBSubnets
      DBParameterGroupName: !Ref DBParamGroup
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  DBSubnets:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnets for RDS cluster"
      SubnetIds:
        - !ImportValue PrivateOne
        - !ImportValue PrivateTwo
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  DBParamGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: Parameter group for RDS cluster
      Family: manfred9.6
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  DBClusterParams:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: Parameter group for RDS cluster
      Family: manfred9.6
      Parameters:
        timezone: "UTC"
      Tags:
        - Key: Project
          Value: !Ref ProjectTag


Outputs:

  DBClusterEndpoint:
    Description: Aurora cluster endpoint
    Value: !GetAtt DBAuroraCluster.Endpoint.Address

  DBReadEndpoint:
    Description: Aurora cluster read endpoint
    Value: !GetAtt DBAuroraCluster.ReadEndpoint.Address
